# Generated by Django 6.0.6 on 2026-06-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_product_gst_rate_product_hsn_code_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='khataprofile',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=12),
        ),
    ]
