# Generated by Django 6.0.6 on 2026-06-16 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_paymentrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('PAYMENT_REMINDER', 'Payment Reminder'), ('TRANSACTION_ALERT', 'Transaction Alert'), ('STATEMENT', 'Account Statement')], max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('message_body', models.TextField()),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('khata_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_logs', to='store_app.khataprofile')),
            ],
        ),
    ]
