# Generated by Django 6.0.6 on 2026-06-16 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_whatsapplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Product-level expiry date (optional). Use ExpiryBatch for per-lot tracking.', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LOW_STOCK', 'Low Stock Alert'), ('OUT_OF_STOCK', 'Out of Stock Alert'), ('HIGH_OUTSTANDING', 'High Outstanding Balance'), ('PENDING_PAYMENT', 'Long Pending Payment'), ('SUPPLIER_DUE', 'Supplier Payment Due'), ('CLOSING_REMINDER', 'Daily Closing Reminder'), ('REPORT_READY', 'Monthly Report Ready'), ('EXPIRY_ALERT', 'Product Expiry Alert')], max_length=20),
        ),
        migrations.CreateModel(
            name='ExpiryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, help_text='Batch/Lot number printed on packaging', max_length=100, null=True)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(help_text='Expiry date for this batch')),
                ('quantity', models.IntegerField(default=0, help_text='Number of units in this batch')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_batches', to='store_app.product')),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
    ]
