# Generated by Django 6.0.6 on 2026-07-01 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0014_promotionalbanner_storeconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='product_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlisted_by', to='store_app.product'),
        ),
    ]
