# Generated by Django 6.0.6 on 2026-07-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0019_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expirybatch',
            name='expiry_date',
            field=models.DateField(db_index=True, help_text='Expiry date for this batch'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('ADDED_TO_KHATA', 'Added to Digital Khata')], db_index=True, default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ORDER_RECEIVED', 'Order Received'), ('PREPARING', 'Preparing Order'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_COMPLETED', 'Payment Completed'), ('ADDED_TO_KHATA', 'Added to Digital Khata'), ('COLLECTED', 'Order Collected'), ('COMPLETED', 'Order Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='ORDER_RECEIVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
